<a href="https://colab.research.google.com/github/lgonzzreyes-boop/Portafolio-TI-Lourdes/blob/main/Copy_of_Untitled9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.read_csv("/content/wine_data_a.csv - wine_data_a.csv.csv")
df

,idx,Alcohol,Malicacid,Ash,Alcalinity_of_ash,Magnesium,Total_phenols,Flavanoids,Nonflavanoid_phenols,Proanthocyanins,Color_intensity,Hue,0D280_0D315_of_diluted_wines,Proline,class
0,0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,1
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,1
2,2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,1
3,3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.8,0.86,3.45,1480,1
4,4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.7,0.64,1.74,740,3
174,174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.3,0.70,1.56,750,3
175,175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.2,0.59,1.56,835,3
176,176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.3,0.60,1.62,840,3
177,177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.2,0.61,1.60,560,3

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   idx                           178 non-null    int64
 1   Alcohol                       178 non-null    float64
 2   Malicacid                     178 non-null    float64
 3   Ash                           178 non-null    float64
 4   Alcalinity_of_ash             178 non-null    float64
 5   Magnesium                     178 non-null    int64
 6   Total_phenols                 178 non-null    float64
 7   Flavanoids                    178 non-null    float64
 8   Nonflavanoid_phenols          178 non-null    float64
 9   Proanthocyanins               178 non-null    float64
 10  Color_intensity               178 non-null    object
 11  Hue                           178 non-null    float64
 12  0D280_0D315_of_diluted_wines  178 non-null    float64
 13  Proline                       178 non-null    int64
 14  class                         178 non-null    int64
dtypes: float64(10), int64(4), object(1)
memory usage: 21.0+ KB

In [ ]:
df['Color_intensity'] = pd.to_numeric(df['Color_intensity'], errors='coerce')
df = df.dropna() # Eliminamos filas con errores si las hubiera

In [ ]:
df.describe()

,idx,Alcohol,Malicacid,Ash,Alcalinity_of_ash,Magnesium,Total_phenols,Flavanoids,Nonflavanoid_phenols,Proanthocyanins,Color_intensity,Hue,0D280_0D315_of_diluted_wines,Proline,class
count,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000,177.000000
mean,88.033898,13.001921,2.336045,2.367006,19.494915,99.819209,2.300226,2.037853,0.361186,1.596271,5.030734,6.073164,2.617232,748.457627,1.932203
std,51.296808,0.813943,1.120308,0.275045,3.349038,14.285286,0.623886,0.995087,0.124486,0.569464,2.295872,68.027356,0.708127,315.106457,0.773078
min,0.000000,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000,1.000000
25%,44.000000,12.360000,1.600000,2.210000,17.200000,88.000000,1.750000,1.220000,0.270000,1.250000,3.210000,0.790000,1.960000,502.000000,1.000000
50%,88.000000,13.050000,1.860000,2.360000,19.500000,98.000000,2.360000,2.140000,0.340000,1.560000,4.680000,0.980000,2.780000,675.000000,2.000000
75%,132.000000,13.680000,3.100000,2.560000,21.500000,107.000000,2.800000,2.880000,0.430000,1.950000,6.200000,1.120000,3.170000,985.000000,3.000000
max,177.000000,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,906.000000,4.000000,1680.000000,3.000000

In [ ]:
df["class"].value_counts()

class
2    71
1    59
3    47
Name: count, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

X = df.iloc[:,:-1]
Y = df.iloc[:,-1]

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.1, random_state=123, )

print("Tamaño set de entrenamiento: ", x_train.shape, y_train.shape)
print("Tamaño set de prueba: ", x_test.shape, y_test.shape)

Tamaño set de entrenamiento:  (159, 14) (159,)
Tamaño set de prueba:  (18, 14) (18,)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

bosque = RandomForestClassifier(random_state=123, oob_score=True)

bosque.fit(x_train, y_train)

RandomForestClassifier(oob_score=True, random_state=123)

In [ ]:
bosque.oob_score_

0.9937106918238994

In [ ]:
len(bosque.estimators_)

100

In [ ]:
bosque.estimators_[3].get_n_leaves()

np.int64(6)

In [ ]:
bosque.oob_decision_function_.shape

(159, 3)

In [ ]:
bosque.oob_decision_function_

array([[1.        , 0.        , 0.        ],
       [0.075     , 0.        , 0.925     ],
       [0.        , 0.17241379, 0.82758621],
       [0.02702703, 0.24324324, 0.72972973],
       [0.02777778, 0.97222222, 0.        ],
       [0.        , 0.97222222, 0.02777778],
       [0.        , 0.05882353, 0.94117647],
       [0.        , 0.13333333, 0.86666667],
       [0.        , 0.27777778, 0.72222222],
       [0.02777778, 0.97222222, 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.94594595, 0.05405405, 0.        ],
       [0.02702703, 0.94594595, 0.02702703],
       [0.        , 1.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.02325581, 0.27906977, 0.69767442],
       [0.        , 0.03125   , 0.96875   ],
       [0.        , 0.        , 1.        ],
       [0.03333333, 0.03333333, 0.93333333],
       [1.        , 0.        , 0.        ],
       [0.97435897, 0.02564103, 0.        ],
       [0.97368421, 0.        , 0.02631579],
       [0.96774194, 0.        , 0.03225806],
       [0.        , 1.        , 0.        ],
       [0.94117647, 0.05882353, 0.        ],
       [0.02702703, 0.89189189, 0.08108108],
       [0.        , 0.06666667, 0.93333333],
       [0.02631579, 0.13157895, 0.84210526],
       [0.        , 1.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.        , 0.94444444, 0.05555556],
       [0.        , 0.96969697, 0.03030303],
       [0.16666667, 0.76190476, 0.07142857],
       [1.        , 0.        , 0.        ],
       [0.92857143, 0.07142857, 0.        ],
       [0.91176471, 0.08823529, 0.        ],
       [1.        , 0.        , 0.        ],
       [0.02564103, 0.97435897, 0.        ],
       [0.97222222, 0.02777778, 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.075     , 0.125     , 0.8       ],
       [0.97222222, 0.02777778, 0.        ],
       [0.04651163, 0.23255814, 0.72093023],
       [0.97297297, 0.02702703, 0.        ],
       [0.28125   , 0.5       , 0.21875   ],
       [0.        , 0.87878788, 0.12121212],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.        , 0.03333333, 0.96666667],
       [0.        , 1.        , 0.        ],
       [0.22580645, 0.77419355, 0.        ],
       [0.07894737, 0.5       , 0.42105263],
       [0.        , 0.        , 1.        ],
       [0.8974359 , 0.1025641 , 0.        ],
       [0.94285714, 0.05714286, 0.        ],
       [0.03225806, 0.22580645, 0.74193548],
       [0.        , 0.08695652, 0.91304348],
       [0.02777778, 0.97222222, 0.        ],
       [0.        , 0.05555556, 0.94444444],
       [0.        , 0.925     , 0.075     ],
       [0.93023256, 0.06976744, 0.        ],
       [0.        , 0.02564103, 0.97435897],
       [0.        , 1.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.14705882, 0.82352941, 0.02941176],
       [0.        , 1.        , 0.        ],
       [0.94594595, 0.05405405, 0.        ],
       [0.81818182, 0.18181818, 0.        ],
       [0.05714286, 0.91428571, 0.02857143],
       [1.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 0.96875   , 0.03125   ],
       [0.        , 0.88571429, 0.11428571],
       [0.        , 1.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.96875   , 0.03125   , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.06976744, 0.72093023, 0.20930233],
       [0.0625    , 0.9375    , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.94871795, 0.02564103, 0.02564103],
       [0.        , 0.        , 1.        ],
       [0.97826087, 0.02173913, 0.        ],
       [0.        , 0.17647059, 0.82352941],
       [0.97368421, 0.        , 0.02631579],
       [0.84090909, 0.13636364, 0.02272727],
       [0.        , 0.11904762, 0.88095238],
       [0.        , 1.        , 0.        ],
       [0.        , 0.2       , 0.8       ],
       [0.58333333, 0.41666667, 0.        ],
       [1.        , 0.        , 0.        ],
       [0.22857143, 0.68571429, 0.08571429],
       [1.        , 0.        , 0.        ],
       [0.        , 0.13157895, 0.86842105],
       [0.        , 0.97058824, 0.02941176],
       [0.        , 1.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 0.        , 1.        ],
       [0.        , 0.65625   , 0.34375   ],
       [1.        , 0.        , 0.        ],
       [0.94736842, 0.05263158, 0.        ],
       [0.92857143, 0.07142857, 0.        ],
       [0.02631579, 0.94736842, 0.02631579],
       [0.03125   , 0.96875   , 0.        ],
       [0.        , 0.97368421, 0.02631579],
       [0.        , 0.05882353, 0.94117647],
       [0.        , 0.08571429, 0.91428571],
       [0.06896552, 0.89655172, 0.03448276],
       [0.94594595, 0.05405405, 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 0.60869565, 0.39130435],
       [0.02564103, 0.97435897, 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 0.96969697, 0.03030303],
       [0.06666667, 0.86666667, 0.06666667],
       [0.        , 0.97222222, 0.02777778],
       [0.        , 0.91666667, 0.08333333],
       [0.        , 0.        , 1.        ],
       [0.        , 0.        , 1.        ],
       [0.        , 0.06896552, 0.93103448],
       [0.        , 0.        , 1.        ],
       [0.94594595, 0.02702703, 0.02702703],
       [0.        , 0.94117647, 0.05882353],
       [1.        , 0.        , 0.        ],
       [0.97560976, 0.02439024, 0.        ],
       [1.        , 0.        , 0.        ],
       [0.06896552, 0.82758621, 0.10344828],
       [0.        , 0.        , 1.        ],
       [0.06451613, 0.93548387, 0.        ],
       [0.        , 0.        , 1.        ],
       [0.        , 0.03333333, 0.96666667],
       [0.        , 1.        , 0.        ],
       [0.97297297, 0.02702703, 0.        ],
       [0.53333333, 0.46666667, 0.        ],
       [1.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 0.89473684, 0.10526316],
       [0.97368421, 0.02631579, 0.        ],
       [0.06666667, 0.76666667, 0.16666667],
       [0.        , 1.        , 0.        ],
       [0.02941176, 0.55882353, 0.41176471],
       [0.93333333, 0.06666667, 0.        ],
       [0.02941176, 0.97058824, 0.        ],
       [0.23076923, 0.71794872, 0.05128205],
       [0.02040816, 0.85714286, 0.12244898],
       [0.02777778, 0.97222222, 0.        ]])

In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score
import numpy as np

oob_probs = bosque.oob_decision_function_

oob_preds = np.argmax(oob_probs, axis=1)

precision = precision_score(y_train, oob_preds, average='macro')
recall = recall_score(y_train, oob_preds, average='macro')
puntaje_f1 = f1_score(y_train, oob_preds, average='macro')

print(f"precisión: {precision:.4f}")
print(f"recall: {recall:.4f}")
print(f"puntaje F1: {puntaje_f1:.4f}")

precisión: 0.0000
recall: 0.0000
puntaje F1: 0.0000

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
print(bosque.get_params())

{'bootstrap': True, 'ccp_alpha': 0.0, 'class_weight': None, 'criterion': 'gini', 'max_depth': None, 'max_features': 'sqrt', 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'monotonic_cst': None, 'n_estimators': 100, 'n_jobs': None, 'oob_score': True, 'random_state': 123, 'verbose': 0, 'warm_start': False}